### ISSUE TITLE
Parsing errors block the editor window

### ISSUE THREAD

**Issue by Sparker95** [Krzmbrzl/SQDev#153]
Hi!
Very often SQDEV fails to parse the file and it causes Eclipse to display error windows. Most often it happens when I haven't finished typing the code.
For instance, I might be typing something like this:
`private _a = [1, 2, ]`
And soon I get an Eclipse error screen which contains:
_An internal error occurred during: "Parsing "test.sqf"...".
java.lang.NullPointerException_
These error windows don't take full focus and I can still type in the editor screen.

**Comment by Krzmbrzl** [comment]
I experienced that myself a few times. This should be solved (or rather reduced) by increasing the parse time delay in the settings so that the Plugin will wait longer before stating to parse the content.

This should at least reduce the times you will encounter this error.


I am currently developing a new parser which should resolve this issue as a "side effect"...

**Comment by Krzmbrzl** [comment]
Oh and one more thing - in case you dindn't know: You can close the error window by pressing Esc. That way you don't have to grab your mouse and the interruption is a little less annoying :)

**Comment by Sparker95** [comment]
Thanks! I just increased the timer for now. Works well. In case that the errors keep coming i just move the error window away.

**Comment by Krzmbrzl** [comment]
Could you please verify that this bug is fixed in the new version 0.7.5?

**Comment by Sparker95** [comment]
Sorry for not answering for so long!
I've downloaded the version 0.7.5. and at first glance the problem is gone, at least I can type arrays safely now.
Thanks!

**Comment by Krzmbrzl** [comment]
Glad to hear that :+1:
